services:
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pm2-cluster
    networks:
      - backend

  pm2-cluster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000-3009:3000-3009" # Expose the API cluster on ports 3000 to 3009
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGHOST: postgrestodo
      PGUSER: todo
      PGPASSWORD: todo
      PGDATABASE: todo_db
      PGPORT: 5432
    depends_on:
      - redis
      - prometheus
      - grafana
      - postgrestodo
    networks:
      - backend

  apache-frontend:
      image: httpd:latest
      container_name: apache-frontend
      ports:
        - "80:80" # Expose Apache on port 8080
      volumes:
        - ./frontend:/usr/local/apache2/htdocs/:ro # Serve the HTML frontend
      depends_on:
        - nginx
      networks:
        - backend

  postgrestodo:
    image: postgres:latest
    container_name: postgrestodo
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Expose Prometheus on port 9090
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000" # Expose Grafana on port 4000 to avoid conflicts with API cluster
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_ENABLED=true
    volumes:
      - ./grafana/dashboards.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana:/var/lib/grafana
    networks:
      - backend

volumes:
  pgdata:
    driver: local
networks:
  backend:
    driver: bridge