services:
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pm2-cluster

  pm2-cluster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000-3009:3000-3009" # Expose the API cluster on ports 3000 to 3009
    environment:
      NODE_ENV: production
    depends_on:
      - redis
      - prometheus
      - grafana

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Expose Prometheus on port 9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000" # Expose Grafana on port 4000 to avoid conflicts with API cluster
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_ENABLED=true
    volumes:
      - ./grafana/dashboards.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana:/var/lib/grafana