global:
  scrape_interval: 15s # Intervalle de collecte des métriques

scrape_configs:
  - job_name: 'todo-api'
    static_configs:
      - targets:
          - 'localhost:3000'
          - 'localhost:3001'
          - 'localhost:3002'
          - 'localhost:3003'
          - 'localhost:3004'
          - 'localhost:3005'
          - 'localhost:3006'
          - 'localhost:3007'
          - 'localhost:3008'
          - 'localhost:3009'
